name: "prepare-build-environment"
description: "Prepare build environment"
runs:
  using: "composite"
  steps:
    - name: Clear disk space
      uses: insightsengineering/disk-space-reclaimer@v1
      with:
        tools-cache: false
        dotnet: false
        large-packages: false

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'corretto'

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        dotnet-quality: 'ga'