name: CI

on:
  push:
    branches:
      - '**'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare Build Environment
        uses: ./.github/workflows/prepare-build-environment

      - uses: actions/cache@v4
        with:
          path: |
            build/gradle-jvm
            ~/.nuget/packages
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-Build-${{ hashFiles('gradlew.bat', 'src/dotnet/*/*.csproj', 'src/dotnet/*.props', 'gradle-wrapper.properties') }}

      - run: ./gradlew :protocol:rdgen --no-daemon
      - run: ./gradlew :buildPlugin -PBuildConfiguration=Release --no-daemon

      - uses: mad9000/actions-find-and-replace-string@5
        id: fix_branch_name
        with:
          source: ${{ github.ref_name }}
          find: '/'
          replace: '-'

      - uses: actions/upload-artifact@v4
        if: github.ref_name == 'master' || github.ref_name == 'dev'
        with:
          name: odata-cli-ui.${{ steps.fix_branch_name.outputs.value }}-${{ github.run_number }}
          path: output
